config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "pages#home"
  get "rules", to: "pages#rules"
  get "print", to: "pages#print"
  get "raceinfo", to: "pages#raceinfo"
  get "founders", to: "pages#founders"
  get "shots", to: "pages#shots"
  get "games/new", to: "games#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/driver.rb
class Driver < ApplicationRecord
  belongs_to :team
  has_many :results
  has_many :players
end

app/models/founder.rb
class Founder < ApplicationRecord
  has_one_attached :photo
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :track
  belongs_to :user
  has_many :results
  has_many :players
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :game
  belongs_to :user
  belongs_to :driver
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :game
  belongs_to :driver
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :drivers
end

app/models/track.rb
class Track < ApplicationRecord
  has_many :games
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :games
  has_many :players
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def new
    @game = Game.new
    @track = find_next_race_track
    @tracks = Track.all
    @tracks_name = [@track.name]
    @tracks.each do |track|
      unless @track.name == track.name
        @tracks_name << track.name
      end
    end
  end

  def create
  end

  private

  # Method to find next race on tha calendar -- Not yet working
  def find_next_race_track
    today = Date.today
    tracks = Track.all
    next_race = tracks.find { |track| track.this_years_date >= today }
    return next_race
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
  end

  def rules
  end

  def print
  end

  def raceinfo
  end

  def founders
    @founder = Founder.first
  end

  def shots
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/games/new.html.erb
<div class="navbar-space">
</div>
<img src="https://media.formula1.com/image/upload/content/dam/fom-website/sutton/2022/Italy/Sunday/1422823415.jpg.transform/9col-retina/image.jpg" alt="race", class= "page-overview-img", crop :fill,>
<div class="container mt-5">

  <h1 class="h1-center" >Create a new game</h1>
  <p class="text-center" >Which Grand Prix are yor creating tha game for?</p>

  <div class="mt-5 text-center">
    <%= form_with url: "/games/new", data: {}, method: :get do |form| %>
      <div class="button-wrapper mb-2">
        <%= form.select :tracks, @tracks_name, {}, { class: "form-dropdown" } %>
      </div>
      <div class="button-wrapper mb-2">
        <%= form.submit "SELECT GAME!", class: "btn button-28", data: {} %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>">
    <meta property="og:type" content="website">
    <meta property="og:url" content="<%= request.original_url %>">
    <meta property="og:image" content="<%= meta_image %>">
    <meta property="og:description" content="<%= meta_description %>">
    <meta property="og:site_name" content="<%= meta_title %>">

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <%# <title>F1 Shot Race</title> %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= favicon_link_tag "shot-race-favicon.png", rel: "icon", type: "image/png" %>

    <!-- To prepare app for add to homescreen (A2HS) -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">

    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <%= render 'shared/ios_pwa_links' %>
  </head>

  <body>
    <%= render "/shared/navbar" %>
    <%= render "shared/flashes" %>
    <div class="header-space">
    </div>

    <%= yield %>

    <%= render "/shared/footer" %>
  </body>
</html>

app/views/pages/_megadriver.html.erb
<div class="container">
  <h3>Megadriver</h3>
  <ul>
    <li>Before the game start every player picks one of the driver as their <strong>megadriver</strong>. <em>Decide together if it should be allowed to pick the same megadriver or not</em></li>
    <li><strong>Important:</strong> You are not allowed to pick any of the drivers that are currently top two in the driver standing as your megagriver</li>
    <li>In Q3, apart from the normal betting you will also bet on the position your megadriver will finish. <strong>This is the only bet in the competition that is driver specific</strong></li>
    <li>Decide together before the race if you want to have a <strong>backup megadriver</strong>, and in that case which driver that will be. It should be a driver that is likely to make it to Q3. If a player's choosen megadriver is out before Q3, he/she can use the backup one</li>
    <li>If you manage to guess the correct position of your megadriver, you can pass <strong>FIVE</strong> additional shots to the person to the right of you</li>
    <li>If you happen to be so good so you don't have five shots left to pass. Sorry, you'll just pass as many as you have left</li>
  </ul>
  <p><em>Psst, make the game more fun and <%= link_to 'print', print_path, class: "black-link"%> out pictures of the megadivers. 📷</em></p>
</div>

app/views/pages/_mirror.html.erb
<div class="container">
  <h3>Mirroring</h3>
  <p>If you are correct on all five bets in Q1 or Q2 you can <strong>mirror</strong> one shot.</p>
  <p>To mirror a shot mean you can give back one of the shots you got form the player to the left of you. Up to you to decide which shot it should be.</p>
</div>

app/views/pages/_seeting.html.erb
<div class="container">
  <h3>Who sits where</h3>
  <p>The seeting is very important as you pass and will be passed shots form the players next to you. Therefore, draw lots to decide who sist where. And make sure each player knows who to pass shots to and be passed shots from before the game starts.</p>
</div>

app/views/pages/founders.html.erb
<div class="navbar-space">
</div>
<div class="container mt-2">
  <h1 class="mb-4">The Founders</h1>
  <div class="row">
    <div class="founder-card col-12 col-md-6">
        <img src="https://scontent-arn2-1.xx.fbcdn.net/v/t1.6435-9/52991436_10155970977136825_7643756809974448128_n.jpg?_nc_cat=103&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=5gVqNrh4uAAAX-xnZZO&_nc_ht=scontent-arn2-1.xx&oh=00_AfCycCltRwwUpVg0GtDouNBfpDuPYX6HOsnLZRnY1isAxg&oe=643FA02F", class= "avatar-large", crop: :fill, alt= "Michelle">
        <div class="founder-info">
          <h3>Michelle Lacombe</h3>
          <p><em>Founder of F1 Shot Race</em></p>
        </div>
      </div>
      <hr>
      <div class="founder-card col-12 col-md-6">
        <img src="https://scontent-arn2-1.xx.fbcdn.net/v/t31.18172-1/905413_10152880087322814_479612391_o.jpg?stp=c0.16.200.200a_dst-jpg_p200x200&_nc_cat=103&ccb=1-7&_nc_sid=7206a8&_nc_ohc=u4sgUqlZw60AX-h1ZoC&_nc_oc=AQl6l5sZp70Sl1rqJpMLKGICfK_JiOcJmCcx0vFCTyewoTdzsCpRQTrMjghpOKKHcJW2T9ZDrW8qMQUXmZM5Ysgl&_nc_ht=scontent-arn2-1.xx&oh=00_AfAJalj0llCFAqCMmaF2ujRRw7H5ELpCsBwizT243S8T3A&oe=643F8F2C", class= "avatar-large", crop: :fill, alt= "Stina">
        <div class="founder-info">
          <h3>Stina Nilsson Helander</h3>
          <p><em>Founder of F1 Shot Race</em></p>
        </div>
      </div>
      <hr>
      <div class="founder-card col-12 col-md-6">
        <img src="https://scontent.fbma5-1.fna.fbcdn.net/v/t1.18169-9/155771_10151548041677279_2027989454_n.jpg?_nc_cat=108&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=TwYoJ6o0O9AAX_ethkQ&_nc_ht=scontent.fbma5-1.fna&oh=00_AfDMbqG01XFffvxO6xb4yRHwQLK8m0Y-UGmWwM1hySNEIA&oe=6465EB0E", class= "avatar-large", crop: :fill, alt= "Niklas">
        <div class="founder-info">
          <h3>Niclas Westerlund</h3>
          <p><em>Founder of F1 Shot Race</em></p>
        </div>
      </div>
      <hr>
      <div class="founder-card col-12 col-md-6">
        <img src="https://scontent-arn2-1.xx.fbcdn.net/v/t1.6435-1/105427204_10164127208605554_34862610413776893_n.jpg?stp=dst-jpg_p200x200&_nc_cat=107&ccb=1-7&_nc_sid=7206a8&_nc_ohc=1K7afvAbd2UAX-5dD0V&_nc_ht=scontent-arn2-1.xx&oh=00_AfBLapymtoP0LWn8DhM1qz2I7la4uVgi_8loqLXJtSSHgg&oe=643F9C50", class= "avatar-large", crop: :fill, alt= "Anders">
        <div class="founder-info">
          <h3>Anders Pettersson</h3>
          <p><em>Founder of F1 Shot Race</em></p>
        </div>
      </div>
      <hr>
      <div class="founder-card col-12 col-md-6">
        <%= cl_image_tag @founder.photo.key, class: "avatar-large", crop: :fill, alt: "Julia"%>
        <div class="founder-info">
          <h3><%= @founder.name %></h3>
          <p><em><%= @founder.description %></em></p>
        </div>
      </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner">
  <div class="container">
    <h1>Formula 1 Qualifying <strong>Shot Race</strong></h1>
    <p>The best drinking game you have ever played</p>
  </div>
</div>

<div class="container mt-3">
  <div class="row">
    <div class="col-12 col-md-2">
      <p>Introduction</p>
    </div>
    <div class="col-12 col-md-10">
      <p>In the F1 qualifying shot-race we have combined watching the best sport with a fun game. Meet up with your friends and join us in playing the best drinking game in the world.</p>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-12 col-md-2">
      <p>The Game</p>
    </div>
    <div class="col-12 col-md-10">
      <p>The game is simple and played while watching the qualification.</p>
      <p>Each player start with 20 shots, two of each kind representing the different teams. The players uses the shots to bet on what they think the result of the qualification will be. The player who guess best wins. Simple.</p>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-12 col-md-2">
      <p>The Shots</p>
    </div>
    <div class="col-12 col-md-10">
      <p>Preparing the shots are of course an important part of the game. Each type of shot should represent a team, either by color or in other ways. Redbull vodka for Redbull perhaps?</p>
    </div>
  </div>

  <br>

  <div class="button-wrapper mb-2 row">
    <div class="button-div col-12 col-md-4">
      <%= link_to 'THE GAME', rules_path, class: "btn button-28"%>
    </div>
    <div class="button-div col-12 col-md-4">
      <%= link_to 'THE SHOTS', shots_path, class: "btn button-28"%>
    </div>
    <div class="button-div col-12 col-md-4">
      <%= link_to 'RACE INFO', raceinfo_path, class: "btn button-28"%>
    </div>
  </div>
<br>
</div>

app/views/pages/print.html.erb
<div class="navbar-space">
</div>
<div class="container mt-2">
  <h1>Print</h1>
  <p>Links will be added soon</p>
  <div class="space-div">
  </div>
</div>

app/views/pages/raceinfo.html.erb
<div class="navbar-space">
</div>
<div class="container mt-2">
  <h1>Formula 1 Qualification Information</h1>
</div>
<img src="https://media.formula1.com/image/upload/content/dam/fom-website/sutton/2022/Italy/Sunday/1422823415.jpg.transform/9col-retina/image.jpg" alt="race", class= "page-overview-img", crop :fill,>

<div class="container mt-2">
  <p>The F1 shot race is played while watching the F1 qualification. Therefore, it's ofcourse important to understand how the qulaification works. We'll give you the basics.</p>
  <p><em>You can also find more infomration on the official <a class="black-link", href="https://www.formula1.com/"> Formula 1 webpage</a>.</em></p>
  <h3>Cars and Teams</h3>
  <p>In Formula 1 there are ten teams, with two drivers each, that is competing.</p>
  <h3>Qualification basics</h3>
  <p>Qualification always takes place before a race. The qualification sets the start grid for the race (alternatively the sprint race) the day after.</p>
  <p>The qualification consist of three rounds, Q1, Q2 and Q3. During each round the cars are trying to set the fastest lap time possible. The fastest lap-time set by each car defines the result of each round.</p>
  <p>During the first two rounds, Q1 and Q2, the five slowest cars are eliminated and are not allowed to participate in the next round. The result of the last round, Q3, decides the position of the best ten cars.</p>
</div>

app/views/pages/rules.html.erb
<div class="navbar-space">
</div>
<div class="container mt-2">
  <h1 class="h1-center">The Game</h1>
</div>
  <%= image_tag "rules-overview.png", class: "page-overview-img", crop: :fill, alt: "rules" %>
<div class="container mt-3">
  <h3>Preparations</h3>
  <ul>
    <li>Prepare the <%= link_to 'shots', shots_path, class: "black-link"%></li>
    <li>Draw lots about <a class="black-link", href="#seeting">who sits where</a></li>
    <li>Each player select a <a class="black-link", href="#megadriver">megadriver</a></li>
    <li><%= link_to 'Print', print_path, class: "black-link"%> the rules and the shot list</li>
  </ul>
  <h3>Before start</h3>
    <ul>
    <li>Each player brings 20 shots, two of each type, to his/her dedicated place</li>
    <li><strong>Before</strong> Q1 starts, each player bet which cars he/she think will be out in Q1. Note that the bets are NOT driver sprcific</li>
    <li>Sit back and enjoy Q1 😎</li>
  </ul>
  <p><em>Pssst, if you are not sure about how an F1 qualification work, you can read about it in the <%= link_to 'race info', raceinfo_path, class: "black-link"%></em>.</p>
  <h3>Between Q1 and Q2</h3>
  <p>Be aware, the most urgent thing to do between Q1 and Q2 is to <strong>make your bets for Q2</strong> as that has to be done before Q2 starts. You will have all of Q2 to drink your shots form Q1.</p>
  <ul>
    <li>The shots you guessed <strong>correct</strong> in Q1 you can pass to the player to the <strong>right</strong> of you</li>
    <li>The shots you guessed <strong>wrong</strong> in Q1 you will drink yourself</li>
    <li>If you guessed <strong>all five shots correct</strong> in Q1, you can <a class="black-link", href="#mirror">mirror</a> one shot</li>
    <li>You have to have finished all shots form Q1 before end of Q2</li>
  </ul>
  <h3>Q2</h3>
  <p>Q2 works exactly the same way and with the same rules as Q1. Just be aware that you only have the shots that was not used in Q1 left to bet with.</p>
  <h3>Q3 Betting</h3>
  <ul>
    <li>In Q3, you have to bet on the exact positions the cars will finish, from P1 to P10</li>
    <li>You also have to place your <a class="black-link", href="#megadriver">megadriver</a> at the position you think he will finish</li>
    <li>Drinking works the same as before, you drink the incorrect ones and pass the corect ones to the right</li>
  </ul>
  <h3>Who wins?</h3>
  <p>After qualifying is over and all players have finished their shots, the player who has drunk the <strong>least amount of shots</strong> win! 🎇</p>
  <p>An easy way to keep track of how many shots each person has had is to build a tower of all empty shot glasses.</p>
  <div class="rule-summary">
   <h3>Rule Summary</h3>
    <ul>
      <li>You drink the shots you guessed wrong</li>
      <li>The player to the right of you drink the shots you guessed correct</li>
      <li>That means you drink the correct guessed shots of the person to the left of you</li>
      <li>All bets have to be made before the start of a qualifying round</li>
      <li>All shots have to be drunk before the end of the qualifying round after the one they came from</li>
      <li>Player who drunk the least amount of shots wins!</li>
    </ul>
   </div>
   <br>
  <div id="seeting">
  <%= render "seeting"%>
  </div>
  <div id="megadriver">
    <%= render "megadriver"%>
  </div>
    <div id="mirror">
    <%= render "mirror"%>
  </div>
</div>

app/views/pages/shots.html.erb
<div class="navbar-space">
</div>
<div class="container mt-2">
  <h1>The Shots</h1>
</div>
  <%= image_tag "the-shots.png", class: "page-overview-img", crop: :fill, alt: "rules" %>
<div class="container mt-2">
  <p><em>Before you start preparing the shots, consider that each player will drink on average 20 shots which is a lot. We recommend to not use strong liqour. If you do, keep those shots small! The game is fun enough in itself 😎</em></p>
  <h3>What shots</h3>
  <p>To play the game you need ten different types of shots. Each type representing a team.</p>
  <p>Basic idea is to pick shots that has the same color as the team it represents. That can however be difficult as some colors are overrepresented by the teams...</p>
  <p>You can also try to make the type of shot have a connection with the team or one of the drivers.</p>
  <p>Some examples:</p>
  <ul>
    <li><em>Redbull vodka</em> for <em>Redbull</em></li>
    <li><em>Italian red wine</em> for <em>Alfa Romeo</em></li>
    <li><em>Ferarri sparking wine</em> for <em>Ferrari</em></li>
    <li><em>Sake</em> for <em>AlphaTauri (Yuki)</em></li>
  </ul>
  <p>Ses one example of a shot line-up above, and be creative! 🎨</p>

  <h3>Amount of shots</h3>
  <p>Each player will start the game with 20 shots, two of each type.</p>
  <p>So when you prepare for the shots, think two times the number of players who will participate, per type of shot.</p>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<%# <footer class="bg-light text-center text-lg-start footer-size f1-footer">
  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    F1 Qualifying Shot Race 2023
  </div>
  <!-- Copyright -->
</footer> %>

<div class="footer">
  <%# <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div> %>
  <div class="footer-copyright">
    F1 Qualifying Shot Race 2023
  </div>
</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">
          <%= image_tag "shot-race.logo.png", alt: "Logo", class:"navbar-logo" %>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
            <li class="nav-item active">
              <%= link_to '| Home', root_path, class: "nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to '| The Game', rules_path, class: "nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to '| The Shots', shots_path, class: "nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to '| Race Info', raceinfo_path, class: "nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to '| The Founders', founders_path, class: "nav-link"%>
            </li>
          </ul>
        </div>
      </div>
    </div>